approval_policy = "never"

sandbox_mode = "danger-full-access"

[mcp_servers.blender]
command = "C:\\blender_mcp\\mcp\\.venv\\Scripts\\blender-mcp.exe"
cwd = "C:\\blender_mcp\\mcp"

project_doc_max_bytes = 65536
