# Crash Information
AppName: HOI4 
AppVersion: Operation Postern v1.19.2.0.a729 
SCMBranch: HEAD 
SCMCommit: a729d47bd1c55457e6886b6eeb2fcdef4ac05057 
SCMTimeStamp: "2026-06-29 15:17:03 +0200" 
DateTime: "2026-08-15 10:59:20 +0300" 
BuildType: Release 
Platform: Windows 
Architecture: 64-bit 
OperatingSystem: Windows 11 x86_64 
SystemLanguage: en 
CPUModel: AMD Ryzen 5 7500F 6-Core Processor              
CPUSpeed: 0 
CPUPhysicalCores: 6 
CPULogicalCores: 12 
SystemMemory: 32375 
LaunchArguments: --debug 

# Application Specific Data 
IsLiveBuild: true 
debug: 1 
DataChecksum: 
AppChecksum: 
HasMods: true
Mods: Chaos Redux
IsOldSave: false
