l_english:
chaosx.settings.export.empty: ""
chaosx.settings.export.payload: "\n[GetChaosxSettingsExportScalarRows][GetChaosxSettingsExportEventRows][GetChaosxSettingsExportClusterRows][GetChaosxSettingsExportEvolutionRows]"
chaosx.settings.export.event_row: "event.[?settings_export_event_id|.0]=[?settings_export_event_value|.0]\n[GetChaosxSettingsExportEventRows]"
chaosx.settings.export.cluster_row: "event_cluster.[?settings_export_cluster_id|.0]=[?settings_export_cluster_value|.0]\n[GetChaosxSettingsExportClusterRows]"
chaosx.settings.export.evolution_row: "evolution.[?settings_export_evolution_event_id|.0].[?settings_export_evolution_type|.0].[?settings_export_evolution_stage|.0]=[?settings_export_evolution_value|.0]\n[GetChaosxSettingsExportEvolutionRows]"
chaosx.settings.export.scalar_row: "[GetChaosxSettingsExportScalarToken]=[?settings_export_scalar_value]\n[GetChaosxSettingsExportScalarRows]"
