#!/usr/bin/env python3
"""
sync_qoder_agents.py — one-way Codex → Qoder subagent synchronization.

Chaos Redux runs a dual-runtime agent workflow:

  * Codex runtime  : .codex/agents/*.toml   (CANONICAL authoring source)
  * Qoder runtime  : .qoder/agents/*.md     (GENERATED, do not hand-edit)

This script regenerates every Qoder subagent definition from its Codex TOML
source. It never reads from or writes to `.codex/`; the Codex workflow stays
byte-for-byte intact. Run it whenever a `.codex/agents/*.toml` definition
changes:

    python .tools/sync_qoder_agents.py

Conversion rules
----------------
1. `name` is converted from snake_case to hyphen-case because Qoder only
   accepts lowercase letters and hyphens
   (`chaosx_repo_explorer` -> `chaosx-repo-explorer`).
2. `description` is copied verbatim into the YAML frontmatter.
3. `developer_instructions` becomes the Markdown system-prompt body, with a
   small set of runtime-neutral substitutions (see BODY_SUBSTITUTIONS).
4. Codex-only fields (`model`, `model_reasoning_effort`, `sandbox_mode`,
   `nickname_candidates`) are dropped; Qoder has no equivalent.
5. The `tools` frontmatter field is derived from the project authority model
   (see the chaos-redux-subagents skill): read-only and plan-only agents get
   no edit tools, patch-capable agents get edit tools, and asset/research
   agents additionally get web tools. Authority discipline beyond tool
   gating is enforced by the system-prompt body, which is authoritative.
6. `.qoder/agents/README.md` is regenerated with the canonical name mapping.

Output is idempotent: files are rewritten only when their content changes.
Stale `.md` files without a TOML source are reported, never deleted.
"""

import re
import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # Python 3.9 / 3.10 fallback
    except ModuleNotFoundError:
        sys.exit(
            "ERROR: no TOML parser available. Install tomli "
            "(python -m pip install tomli) or run on Python 3.11+."
        )

MOD_ROOT = Path(__file__).resolve().parent.parent
CODEX_AGENTS = MOD_ROOT / ".codex" / "agents"
QODER_AGENTS = MOD_ROOT / ".qoder" / "agents"

# Runtime-neutral substitutions applied to developer_instructions. Each tuple
# is (regex pattern, replacement). Keep this list mechanical and minimal; the
# TOML body remains the canonical wording.
BODY_SUBSTITUTIONS = [
    (
        r"fork_context=false",
        "a fully explicit, self-contained prompt (no inherited conversation context)",
    ),
    (
        r"Agent Nudger writes",
        "UI-assisted writes",
    ),
]

# Authority classes from the chaos-redux-subagents skill. Qoder tool access is
# coarse, so the system-prompt body remains the authoritative scope contract.
TOOLS_READONLY = "Read, Grep, Glob, Bash, Write"        # gameplay read-only; may write handoff reports
TOOLS_PATCH = "Read, Grep, Glob, Bash, Edit, Write"     # patch-capable inside task scope
TOOLS_ASSET_WEB = TOOLS_PATCH + ", WebFetch, WebSearch" # asset production and sourced research

AUTHORITY = {
    # Read-only agents (may only write requested reports/handoffs).
    "chaosx_repo_explorer": TOOLS_READONLY,
    "chaosx_event_completion_auditor": TOOLS_READONLY,
    "chaosx_ai_probability_auditor": TOOLS_READONLY,
    # Plan-only agent (writes specs/addenda/handoffs, never gameplay).
    "chaosx_improvement_loop_planner": TOOLS_READONLY,
    # Documentation curator (patch-capable for documentation surfaces only).
    "chaosx_documentation_curator": TOOLS_PATCH,
    # Active small-patch agents.
    "chaosx_scripted_system_architect": TOOLS_PATCH,
    "chaosx_decision_mission_auditor": TOOLS_PATCH,
    "chaosx_focus_tree_auditor": TOOLS_PATCH,
    "chaosx_country_package_auditor": TOOLS_PATCH,
    "chaosx_localisation_auditor": TOOLS_PATCH,
    "chaosx_event_ui_worker": TOOLS_PATCH,
    "chaosx_skill_maintainer": TOOLS_PATCH,
    "chaosx_spreadsheet_doc_worker": TOOLS_PATCH,
    # Asset production and research agents.
    "chaosx_asset_source_researcher": TOOLS_ASSET_WEB,
    "chaosx_generated_event_art": TOOLS_ASSET_WEB,
    "chaosx_icon_artist": TOOLS_ASSET_WEB,
    "chaosx_portrait_creator": TOOLS_ASSET_WEB,
    "chaosx_super_event_text_researcher": TOOLS_ASSET_WEB,
    "chaosx_super_event_audio_researcher": TOOLS_ASSET_WEB,
    "chaosx_3d_model_pipeline": TOOLS_ASSET_WEB,
}

GENERATED_BANNER = (
    "<!-- GENERATED FILE: regenerated from .codex/agents/{src} by\n"
    "     python .tools/sync_qoder_agents.py. Do not hand-edit;\n"
    "     change the Codex TOML source and rerun the sync script. -->\n"
)

README_TEMPLATE = """<!-- GENERATED FILE: regenerated by python .tools/sync_qoder_agents.py. -->
# Qoder Subagents (Generated)

Every file in this folder is generated from the canonical Codex definitions in
`.codex/agents/` by `python .tools/sync_qoder_agents.py`. Do not hand-edit
them. To change a subagent, edit its `.codex/agents/<name>.toml` source and
rerun the sync script.

## Name mapping

Qoder only allows lowercase letters and hyphens in subagent names, so the
canonical snake_case Codex identifiers map to hyphen-case Qoder identifiers.

| Canonical (Codex) | Qoder | Authority |
| --- | --- | --- |
{rows}

Authority classes follow the `chaos-redux-subagents` skill: read-only,
plan-only, documentation curation, active small-patch, asset production, or
3D model routing. Tool access in the frontmatter is coarse; the system prompt
body of each agent is the authoritative scope contract.
"""


def load_toml(path):
    with open(path, "rb") as handle:
        return tomllib.load(handle)


def apply_substitutions(body):
    result = body
    for pattern, replacement in BODY_SUBSTITUTIONS:
        result = re.sub(pattern, replacement, result)
    return result.strip() + "\n"


def yaml_quote(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"{}"'.format(escaped)


def render_agent(name, description, body, src_name):
    qoder_name = name.replace("_", "-")
    tools = AUTHORITY.get(name)
    lines = ["---", "name: {}".format(qoder_name), "description: {}".format(yaml_quote(description))]
    if tools:
        lines.append("tools: {}".format(tools))
    lines.append("---")
    lines.append("")
    header = GENERATED_BANNER.format(src=src_name)
    return "\n".join(lines) + header + "\n" + body


def write_if_changed(path, content):
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    with open(path, "w", encoding="utf-8", newline="") as handle:
        handle.write(content)
    return True


def authority_label(tools):
    if tools == TOOLS_READONLY:
        return "read-only / plan-only"
    if tools == TOOLS_PATCH:
        return "patch-capable"
    if tools == TOOLS_ASSET_WEB:
        return "asset / research (web)"
    return "unmapped"


def main():
    if not CODEX_AGENTS.is_dir():
        sys.exit("ERROR: canonical source folder not found: {}".format(CODEX_AGENTS))
    QODER_AGENTS.mkdir(parents=True, exist_ok=True)

    created, updated, unchanged, unmapped = [], [], [], []
    expected_files = {"README.md"}
    rows = []

    for toml_path in sorted(CODEX_AGENTS.glob("*.toml")):
        data = load_toml(toml_path)
        name = data.get("name") or toml_path.stem
        description = data.get("description", "").strip()
        instructions = data.get("developer_instructions", "").strip()
        if not description or not instructions:
            sys.exit("ERROR: {} is missing description or developer_instructions".format(toml_path))

        if name not in AUTHORITY:
            unmapped.append(name)

        qoder_name = name.replace("_", "-")
        out_path = QODER_AGENTS / "{}.md".format(qoder_name)
        expected_files.add(out_path.name)
        content = render_agent(name, description, apply_substitutions(instructions), toml_path.name)

        if not out_path.exists():
            write_if_changed(out_path, content)
            created.append(qoder_name)
        elif write_if_changed(out_path, content):
            updated.append(qoder_name)
        else:
            unchanged.append(qoder_name)

        rows.append(
            "| `{}` | `{}` | {} |".format(name, qoder_name, authority_label(AUTHORITY.get(name, "")))
        )

    readme = README_TEMPLATE.format(rows="\n".join(rows))
    write_if_changed(QODER_AGENTS / "README.md", readme)

    stale = sorted(
        p.name
        for p in QODER_AGENTS.glob("*.md")
        if p.name not in expected_files
    )

    print("Synced {} agent(s): {} created, {} updated, {} unchanged.".format(
        len(created) + len(updated) + len(unchanged), len(created), len(updated), len(unchanged)))
    if created:
        print("  created: {}".format(", ".join(created)))
    if updated:
        print("  updated: {}".format(", ".join(updated)))
    if unmapped:
        print("  WARNING: no authority mapping (tools field omitted): {}".format(", ".join(unmapped)))
    if stale:
        print("  WARNING: stale file(s) without a TOML source (not deleted): {}".format(", ".join(stale)))


if __name__ == "__main__":
    main()
