#!/usr/bin/env python3
"""
sync_cursor_agents.py — one-way Codex → Cursor subagent synchronization.

Chaos Redux keeps Codex as the primary authoring workflow:

  * Codex runtime  : .codex/agents/*.toml   (CANONICAL authoring source)
  * Cursor runtime : .cursor/agents/*.md    (GENERATED, do not hand-edit)

This script regenerates every Cursor subagent definition from its Codex TOML
source. It never writes to `.codex/`. Run it whenever a
`.codex/agents/*.toml` definition changes:

    python .tools/sync/sync_cursor_agents.py

Also rerun `python .tools/sync/sync_qoder_agents.py` in the same change so Qoder
stays aligned. Do not treat generated Cursor files as a second authoring
source.

Conversion rules
----------------
1. `name` is converted from snake_case to hyphen-case because Cursor subagent
   identifiers use lowercase letters and hyphens
   (`chaosx_repo_explorer` -> `chaosx-repo-explorer`).
2. `description` is copied verbatim into the YAML frontmatter.
3. `developer_instructions` becomes the Markdown system-prompt body, with a
   small set of runtime-neutral substitutions (see BODY_SUBSTITUTIONS).
4. Codex-only fields (`model`, `model_reasoning_effort`, `sandbox_mode`,
   `nickname_candidates`) are dropped. Cursor gets `model: inherit` so the
   parent session chooses the model.
5. Cursor has no Codex-style tool allowlist. Do not emit `readonly: true`:
   even read-only and plan-only agents may write requested handoffs. Authority
   is enforced by the system-prompt body. Emit only Cursor frontmatter fields:
   `name`, `description`, and `model: inherit`.
6. Write only one `.md` file per subagent into `.cursor/agents/`. Never write
   README or other non-agent markdown there; Cursor loads every `*.md` in that
   folder as a Task-tool subagent. The name mapping is written to
   `.cursor/agent-map.md`.

Output is idempotent: files are rewritten only when their content changes.
Stale `.md` files without a TOML source are reported, never deleted.
"""

import re
import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # Python 3.9 / 3.10 fallback
    except ModuleNotFoundError:
        sys.exit(
            "ERROR: no TOML parser available. Install tomli "
            "(python -m pip install tomli) or run on Python 3.11+."
        )

MOD_ROOT = Path(__file__).resolve().parents[2]
CODEX_AGENTS = MOD_ROOT / ".codex" / "agents"
CURSOR_DIR = MOD_ROOT / ".cursor"
CURSOR_AGENTS = CURSOR_DIR / "agents"
CURSOR_AGENT_MAP = CURSOR_DIR / "agent-map.md"

# Runtime-neutral substitutions applied to developer_instructions. Each tuple
# is (regex pattern, replacement). Keep this list mechanical and minimal; the
# TOML body remains the canonical wording.
BODY_SUBSTITUTIONS = [
    (
        r"fork_context=false",
        "a fully explicit, self-contained prompt (no inherited conversation context)",
    ),
    (
        r"Agent Nudger writes",
        "UI-assisted writes",
    ),
]

# Authority classes from the chaos-redux-subagents skill. Cursor has no
# frontmatter tool allowlist, so this map is documentation-only and must stay
# aligned with `.tools/sync/sync_qoder_agents.py`.
AUTHORITY = {
    "chaosx_repo_explorer": "read-only / plan-only",
    "chaosx_event_completion_auditor": "read-only / plan-only",
    "chaosx_ai_probability_auditor": "read-only / plan-only",
    "chaosx_improvement_loop_planner": "read-only / plan-only",
    "chaosx_documentation_curator": "patch-capable",
    "chaosx_scripted_system_architect": "patch-capable",
    "chaosx_decision_mission_auditor": "patch-capable",
    "chaosx_focus_tree_auditor": "patch-capable",
    "chaosx_country_package_auditor": "patch-capable",
    "chaosx_localisation_auditor": "patch-capable",
    "chaosx_event_ui_worker": "patch-capable",
    "chaosx_skill_maintainer": "patch-capable",
    "chaosx_spreadsheet_doc_worker": "patch-capable",
    "chaosx_asset_source_researcher": "asset / research (web)",
    "chaosx_generated_event_art": "asset / research (web)",
    "chaosx_icon_artist": "asset / research (web)",
    "chaosx_portrait_creator": "asset / research (web)",
    "chaosx_super_event_text_researcher": "asset / research (web)",
    "chaosx_super_event_audio_researcher": "asset / research (web)",
    "chaosx_3d_model_pipeline": "asset / research (web)",
}

AGENT_MAP_TEMPLATE = """<!-- GENERATED FILE: regenerated by python .tools/sync/sync_cursor_agents.py. -->
# Cursor Subagent Map

Every file in `.cursor/agents/` is a Cursor project subagent: Markdown with
YAML frontmatter (`name`, `description`, `model`) plus a prompt body. Cursor
loads each of those files into the Task tool. Do not put README or other
non-agent Markdown in `.cursor/agents/`.

Regenerate after Codex TOML changes:

```text
python .tools/sync/sync_cursor_agents.py
```

Codex remains the primary workflow. `.codex/agents/*.toml` files are Codex
definitions, not Cursor subagent prompts. Spawn the hyphen-case Cursor name
from this table (`/chaosx-repo-explorer`, or Task `subagent_type` matching
that name). Cursor isolates subagent context; the parent prompt must still be
fully explicit.

| Canonical (Codex) | Cursor | Authority |
| --- | --- | --- |
{rows}

Authority classes follow the `chaos-redux-subagents` skill. Cursor has no
Codex-style tool allowlist; the prompt body is the scope contract.
"""


def load_toml(path):
    with open(path, "rb") as handle:
        return tomllib.load(handle)


def apply_substitutions(body):
    result = body
    for pattern, replacement in BODY_SUBSTITUTIONS:
        result = re.sub(pattern, replacement, result)
    return result.strip() + "\n"


def yaml_quote(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"{}"'.format(escaped)


def render_agent(name, description, body, src_name):
    cursor_name = name.replace("_", "-")
    lines = [
        "---",
        "# Generated from .codex/agents/{} by python .tools/sync/sync_cursor_agents.py. Do not hand-edit.".format(
            src_name
        ),
        "name: {}".format(cursor_name),
        "description: {}".format(yaml_quote(description)),
        "model: inherit",
        "---",
        "",
        body.rstrip(),
        "",
    ]
    return "\n".join(lines)


def write_if_changed(path, content):
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    with open(path, "w", encoding="utf-8", newline="") as handle:
        handle.write(content)
    return True


def main():
    if not CODEX_AGENTS.is_dir():
        sys.exit("ERROR: canonical source folder not found: {}".format(CODEX_AGENTS))
    CURSOR_DIR.mkdir(parents=True, exist_ok=True)
    CURSOR_AGENTS.mkdir(parents=True, exist_ok=True)

    created, updated, unchanged, unmapped = [], [], [], []
    expected_files = set()
    rows = []

    for toml_path in sorted(CODEX_AGENTS.glob("*.toml")):
        data = load_toml(toml_path)
        name = data.get("name") or toml_path.stem
        description = data.get("description", "").strip()
        instructions = data.get("developer_instructions", "").strip()
        if not description or not instructions:
            sys.exit("ERROR: {} is missing description or developer_instructions".format(toml_path))

        if name not in AUTHORITY:
            unmapped.append(name)

        cursor_name = name.replace("_", "-")
        out_path = CURSOR_AGENTS / "{}.md".format(cursor_name)
        expected_files.add(out_path.name)
        content = render_agent(name, description, apply_substitutions(instructions), toml_path.name)

        if not out_path.exists():
            write_if_changed(out_path, content)
            created.append(cursor_name)
        elif write_if_changed(out_path, content):
            updated.append(cursor_name)
        else:
            unchanged.append(cursor_name)

        rows.append(
            "| `{}` | `{}` | {} |".format(
                name, cursor_name, AUTHORITY.get(name, "unmapped")
            )
        )

    write_if_changed(CURSOR_AGENT_MAP, AGENT_MAP_TEMPLATE.format(rows="\n".join(rows)))

    stale = sorted(
        p.name
        for p in CURSOR_AGENTS.glob("*.md")
        if p.name not in expected_files
    )

    print("Synced {} agent(s): {} created, {} updated, {} unchanged.".format(
        len(created) + len(updated) + len(unchanged), len(created), len(updated), len(unchanged)))
    if created:
        print("  created: {}".format(", ".join(created)))
    if updated:
        print("  updated: {}".format(", ".join(updated)))
    if unmapped:
        print("  WARNING: no authority mapping: {}".format(", ".join(unmapped)))
    if stale:
        print("  WARNING: stale file(s) without a TOML source (not deleted): {}".format(", ".join(stale)))


if __name__ == "__main__":
    main()
